CDOT CV Manager Theme Generator
CDOT-CV/keycloakify-starter pull request #1
Opened 2023-11-07 18:13 UTC by Michael7371

Added the required changes to the keycloakify-starter repo for the CDOT CV Manager theme.

2023-12-01 02:23 UTC, drewjj approved these changes
Looks good to me.

2024-01-26 22:01 UTC, payneBrandon commented on .github/workflows/ci.yaml
> +  build:
I hadn't dug into this yaml file previously, but it looks like we're triggering on push and pull requests to the main branch. Does that mean any PR will trigger the full CI? It looks like we have a build and release below, that may not be what we want

2024-01-26 22:10 UTC, payneBrandon requested changes
Just the one question about the CI

2024-01-26 22:38 UTC, payneBrandon approved these changes
lgtm!

2024-01-26 22:38 UTC, merged